const Players = [{name: "Jason", rank: "Platinum" , game: "Smite", status: "Mentor", bio: "I like Smite"},
{name: "Britania", game: "LoL", rank:"Grandmaster", status: "Open", bio: "I play league"},
{name: "Ryan", game: "Apex Legends", rank: "Silver", status: "Closed", bio: "I like Apex Legends"},
{name: "Anas", game: "Apex Legends", rank: "Bronze", status: "Mentor", bio: "I shred at Apex Legends"},
{name: "RS", game: "LoL", rank:"Platinum", status: "Mentor", bio: "YUHHHHHHH"},
{name: "Adhrik", game: "LoL", rank: "Bronze", status: "Closed", bio: "I watched Arcane"},
{name: "Beau", game: "LoL", rank: "Iron", status: "Mentor", bio: "I can teach League"},
{name: "Scott", game: "Apex Legends", rank: "Master", status: "Open", bio: "Down to learn some new stuff!"},
{name: "Nihar", game: "Smite", rank: "Bronze", status: "Closed", bio: "No one is better than me"},
{name: "xX_XTREME_PLAYER_Xx", game: "LoL", rank: "Gold", status: "Mentor", bio: "I haven't showered in two weeks"},
{name: "leagueplayer", game: "LoL", rank: "Gold", status: "Open", bio: "The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start."},
{name: "Rick Astley", game: "Smite", rank: "Grandmaster", status: "Closed", bio: "We're no strangers to love You know the rules and so do I A full commitment's what I'm thinking of You wouldn't get this from any other guy I just wanna tell you how I'm feeling Gotta make you understand Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you We've known each other for so long Your heart's been aching but you're too shy to say it Inside we both know what's been going on We know the game and we're gonna play it And if you ask me how I'm feeling Don't tell me you're too blind to see Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you Never gonna give, never gonna give (Give you up) Weve known each other for so long Your hearts been aching but youre too shy to say it Inside we both know whats been going on We know the game and we're gonna play it I just wanna tell you how I'm feeling Gotta make you understand Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye"}
]

export default Players;

//add rank and in game name